vim.keymap.set("n", "<leader><space>", function()
	Snacks.picker.files()
end)
vim.keymap.set("n", "<leader>/", function()
	Snacks.picker.grep()
end)
vim.keymap.set("n", "[b", "<cmd>bprevious<cr>")
vim.keymap.set("n", "]b", "<cmd>bnext<cr>")
vim.keymap.set("n", "<leader>bd", "<cmd>bdelete<cr>")
vim.keymap.set("n", "<leader>.", function()
	Snacks.picker.buffers()
end)
vim.keymap.set("n", "<leader>cs", function()
	Snacks.picker.lsp_symbols()
end)
vim.keymap.set("n", "<leader>cS", function()
	Snacks.picker.lsp_workspace_symbols()
end)
vim.keymap.set("n", "<leader>r", function()
	Snacks.picker.resume()
end)
vim.keymap.set("n", "<leader>d", "<cmd>Trouble diagnostics toggle<cr>")
