REPO_OWNER=${REPO_OWNER:-robian}
REPO_NAME=${REPO_NAME:-dotfiles2}
REPO_SLUG=${REPO_SLUG:-$REPO_OWNER/$REPO_NAME}
REPO_HTTPS_URL=${REPO_HTTPS_URL:-https://github.com/$REPO_SLUG.git}
REPO_SSH_URL=${REPO_SSH_URL:-git@github.com:$REPO_SLUG.git}
